require:
- rubocop-rspec
- rubocop-performance

# Line length is more trouble than it's worth, IMO. Be reasonable.
Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    # Specs are generally long.
    - 'spec/**/*'

RSpec/NestedGroups:
  Enabled: false

# Enable newly released cops:
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
